export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAIL = 'CREATE_ADDRESS_FAIL'

export const MY_ADDRESS_REQUEST = 'MY_ADDRESS_REQUEST'
export const MY_ADDRESS_SUCCESS = 'MY_ADDRESS_SUCCESS'
export const MY_ADDRESS_FAIL = 'MY_ADDRESS_FAIL'

export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST'
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS'
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS";