export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAIL = 'CREATE_ADDRESS_FAIL'

export const MY_ADDRESS_REQUEST = 'MY_ADDRESS_REQUEST'
export const MY_ADDRESS_SUCCESS = 'MY_ADDRESS_SUCCESS'
export const MY_ADDRESS_FAIL = 'MY_ADDRESS_FAIL'


export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_RESET = 'DELETE_ADDRESS_RESET'
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL'


export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'
export const UPDATE_ADDRESS_RESET = 'UPDATE_ADDRESS_RESET'
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL'


export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST'
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS'
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL'


export const CLEAR_ERRORS = "CLEAR_ERRORS";