export const CREATE_OFFER_REQUEST = 'CREATE_OFFER_REQUEST'
export const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS'
export const CREATE_OFFER_FAIL = 'CREATE_OFFER_FAIL'

export const ALL_OFFERS_REQUEST = 'ALL_OFFERS_REQUEST'
export const ALL_OFFERS_SUCCESS = 'ALL_OFFERS_SUCCESS'
export const ALL_OFFERS_FAIL = 'ALL_OFFERS_FAIL'


export const DELETE_OFFER_REQUEST = 'DELETE_OFFER_REQUEST'
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS'
export const DELETE_OFFER_RESET = 'DELETE_OFFER_RESET'
export const DELETE_OFFER_FAIL = 'DELETE_OFFER_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS";